codecov:
  notify:
    after_n_builds: 1
coverage:
  range: 70..100
  round: nearest
  precision: 1
  status:
    project:
      default:
        threshold: 5%
    patch:
      default:
        threshold: 20%
        target: 60%
  ignore:
    - "tests/*"
comment:
  layout: "reach, diff, files"
  behavior: once
  after_n_builds: 1
  require_changes: true
