 name: Continuous Integration
 
 on:
   push:
     branches:
     - '*'
   pull_request:
     branches:
     - '*'
   schedule:
     - cron: '59 23 * * *'
   workflow_dispatch:
    inputs:
      version:
        description: Manual CI Run
        default: test
        required: false

 jobs:
   tests:
     name: ${{ matrix.os }}, ${{ matrix.environment-file }}
     runs-on: ${{ matrix.os }}
     timeout-minutes: 30
     strategy:
       matrix:
         os: [ubuntu-latest]
         environment-file: [
            ci/py312-latest.yaml,
         ]
       fail-fast: false

     defaults:
       run:
         shell: bash -l {0}

     steps:
       - name: checkout repo
         uses: actions/checkout@v4
         with:
           fetch-depth: 0 # Fetch all history for all branches and tags.
       
       - name: setup micromamba
         uses: mamba-org/setup-micromamba@v1
         with:
           environment-file: ${{ matrix.environment-file }}
           micromamba-version: "latest"

       - name: install package
         run: "pip install -e ."

       - name: environment info
         run: "micromamba info && micromamba list"
       
       - name: run tests
         run: |
           pytest \
           fastpair/ \
           --verbose \
           -r a \
           --color yes \
           --cov fastpair \
           --cov-append \
           --cov-report term-missing \
           --cov-report xml .
       
       - name: codecov
         uses: codecov/codecov-action@v4
         with:
           token: ${{ secrets.CODECOV_TOKEN }}
